//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/12/2017 23:45:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace EFC_EntityDeveloper
{
    public partial class FlightPassenger {

        public FlightPassenger()
        {
            OnCreated();
        }

        public virtual int FlightFlightNo
        {
            get;
            set;
        }

        public virtual int PassengerPersonID
        {
            get;
            set;
        }

        public virtual Flight Flight
        {
            get;
            set;
        }

        public virtual Passenger Passenger
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          FlightPassenger toCompare = obj as FlightPassenger;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.FlightFlightNo, toCompare.FlightFlightNo))
            return false;
          if (!Object.Equals(this.PassengerPersonID, toCompare.PassengerPersonID))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + FlightFlightNo.GetHashCode();
          hashCode = (hashCode * 7) + PassengerPersonID.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
